site_name: Workshop Orange Handbook
theme: 
  name: material
  logo: images/top-logo.png
  favicon: images/favicon.png
  features: 
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - announce.dismiss
    - navigation.instant
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.sahre
    - search.suggest
  
  palette:

      # palette toggle for dark mode
    - scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode

      # palette toggle for light mode
    - scheme: default
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

nav:
  - Introduction: index.md
  - Pillars:
    - Pillar I - Mindset: pillar1.md
    - Pillar II - Culture, Leadership, Team: pillar2.md
    - Pillar III - Client Services: pillar3.md
    - Pillar IV - Service Delivery: pillar4.md
    - Pillar V - Marketing & Sales: pillar5.md
    - Pillar VI - Financial Intelligence: pillar6.md

    

extra_css:
  - styles/custom.css
